import Head from "next/head";
import Image from "next/image";
import { Poppins, Playfair_Display } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["200", "400", "600", "700", "800"],
});
const playfair = Playfair_Display({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Fauxica</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="wrapper">
        <header>
          <Link href="#">
            <img src="/images/logo.svg" alt="Fauxica Logo" />
          </Link>
          <nav>
            <ul>
              <li>
                <Link href="#" className={`${poppins.className} active`}>
                  Home
                </Link>
              </li>
              <li>
                <Link href="#" className={`${poppins.className}`}>
                  Products
                </Link>
              </li>
              <li>
                <Link href="#" className={`${poppins.className}`}>
                  Gallery
                </Link>
              </li>
              <li>
                <Link href="#" className={`${poppins.className}`}>
                  Contact
                </Link>
              </li>
            </ul>
          </nav>
        </header>

        <main>
          <div className="left-col">
            <h1 className={playfair.className}>
              Quality apparel without the price tag
            </h1>
            <p className={`${poppins.className} subhead`}>
              No need to spend $xxx on apparel just for the names sake. Our
              premium apparel is made from the same stuff.
            </p>
            <div className="cta-btns">
              <Link href="#" className={`${poppins.className} primary-cta`}>
                Browse our collection
              </Link>
              <Link href="#" className={`${poppins.className} secondary-cta`}>
                <span>Spring 23 Collection</span>
                <svg viewBox="0 0 19 8" fill="none">
                  <path
                    d="M18.3536 4.35355C18.5488 4.15829 18.5488 3.84171 18.3536 3.64645L15.1716 0.464466C14.9763 0.269204 14.6597 0.269204 14.4645 0.464466C14.2692 0.659728 14.2692 0.976311 14.4645 1.17157L17.2929 4L14.4645 6.82843C14.2692 7.02369 14.2692 7.34027 14.4645 7.53553C14.6597 7.7308 14.9763 7.7308 15.1716 7.53553L18.3536 4.35355ZM0 4.5H18V3.5H0V4.5Z"
                    fill="black"
                  />
                </svg>
              </Link>
            </div>

            <div className="news">
              <p className={`${poppins.className} employees`}>50K</p>
              <p className={`${poppins.className} details`}>
                We&apos;re proud to announce that we now employ a workflorce of
                over <strong>50,000</strong>. It&apos;s all possible because of
                you.
              </p>
            </div>
          </div>
          <div className="right-col">
            <div className="card card1">
              <div className="card-details">
                <div>
                  <Link
                    href="#"
                    className={`${poppins.className} product-title`}
                  >
                    Fauxica Sport
                  </Link>
                  <p className={poppins.className}>Running shoes</p>
                </div>
                <p className={`${poppins.className} product-price`}>$49</p>
              </div>
            </div>

            <div className="card card2">
              <div className="card-details">
                <div>
                  <Link
                    href="#"
                    className={`${poppins.className} product-title`}
                  >
                    Fauxica Sport
                  </Link>
                  <p className={poppins.className}>Running shoes</p>
                </div>
                <p className={`${poppins.className} product-price`}>$49</p>
              </div>
            </div>

            <div className="card card3">
              <div className="card-details">
                <div>
                  <Link
                    href="#"
                    className={`${poppins.className} product-title`}
                  >
                    Fauxica Sport
                  </Link>
                  <p className={poppins.className}>Running shoes</p>
                </div>
                <p className={`${poppins.className} product-price`}>$49</p>
              </div>
            </div>
          </div>
        </main>
      </div>
    </>
  );
}
